version: '3'

services:

  web:
    image: maven:3.6.0-jdk-8
    restart: always
    container_name: web
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run -Drun.profiles=docker