gcloud beta runtime-config configs variables set flock.fundraising.name Doneasy --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.generate.dayOfMonth 15 --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.collection.dayOfMonth 28 --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.message 'HARTELIJK DANK VOOR UW BIJDRAGE' --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.name Doneasy --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.privateIdentification NL00ZZZ000000000 --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.iban NL00XXXX0000000000 --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.bic INGBNL2A --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.address1 'Address 1' --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.address2 1234AB --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.sepa.country NL --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.successUrl 'https://willemveelenturf.wixsite.com/donate-here-success' --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.donations.failureUrl 'https://willemveelenturf.wixsite.com/donate-here-failure' --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.load-data.enabled true --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set flock.fundraising.load-data.stub true --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.cloud.gcp.sql.enabled true --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.cloud.gcp.sql.database-name fundraising --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.cloud.gcp.sql.instance-connection-name doneasy:europe-west1:doneasy-data --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.jpa.hibernate.ddl-auto update --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.jpa.properties.hibernate.globally_quoted_identifiers true --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.jpa.properties.hibernate.dialect org.hibernate.dialect.MySQL57Dialect --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.security.oauth2.client.registration.google.client-id '213550207512-u9ff6dbohkkecbtbcp1lorufvf9q7cs7.apps.googleusercontent.com' --config-name=fundraising_cloud
gcloud beta runtime-config configs variables set spring.security.oauth2.client.registration.google.client-secret 'HRg7PvS8oYHVv1s11o5g804R' --config-name=fundraising_cloud